name: duckstation-fresh
base: core24
adopt-info: duckstation-fresh-app
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
summary: PlayStation Emulator
description: |
  DuckStation is an simulator/emulator of the Sony PlayStation(TM) console, focusing on playability, speed, and long-term maintainability.
  The goal is to be as accurate as possible while maintaining performance suitable for low-end devices.
  "PlayStation" and "PSX" are registered trademarks of Sony Interactive Entertainment Europe Limited.
  This project is not affiliated in any way with Sony Interactive Entertainment.
grade: stable
confinement: strict
icon: org.duckstation.DuckStation.png

apps:
  duckstation-fresh:
    command-chain: [snap/command-chain/unset-qt_qpa_platform]
    command: usr/bin/duckstation-qt
    desktop: usr/share/applications/org.duckstation.DuckStation.desktop
    common-id: org.duckstation.DuckStation
    environment:
      QT_QPA_PLATFORMTHEME: xdgdesktopportal
      LD_LIBRARY_PATH: $SNAP/lxqt-support-core24/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
      QT_PLUGIN_PATH: $SNAP/lxqt-support-core24/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins:$QT_PLUGIN_PATH
    extensions: [kde-neon-6]
    plugs:
      - screen-inhibit-control
      - home
      - removable-media
      - mount-observe
      - joystick
      - bluez
      - udisks2

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/alsa-lib
  /usr/share/color-schemes:
    symlink: $SNAP/lxqt-support-core24/usr/share/color-schemes
  /usr/share/Kvantum:
    symlink: $SNAP/lxqt-support-core24/usr/share/Kvantum

plugs:
  shared-memory:
    private: true
  lxqt-support-core24:
    content: lxqt-support-core24
    interface: content
    target: $SNAP/lxqt-support-core24
    default-provider: lxqt-support-core24

parts:
  duckstation-fresh-app:
    plugin: nil
    build-packages:
      - wget
    override-build: |
      URL=$(curl -s "https://api.github.com/repos/Kyuyrii/Duckstation-GPL/releases/latest" | grep -o 'https://github.com/Kyuyrii/Duckstation-GPL/releases/download/[^"]*/DuckStation-x64\.AppImage' | head -1)
      wget "$URL"
      chmod +x DuckStation-x64.AppImage
      ./DuckStation-x64.AppImage --appimage-extract
      mv -f squashfs-root/usr $CRAFT_PART_INSTALL/
      sed -i 's|Name=DuckStation|Name=DuckStation Fresh|' $CRAFT_PART_INSTALL/usr/share/applications/org.duckstation.DuckStation.desktop

      VERSION=$(echo "$URL" | sed -n 's#.*/download/v\([^/]*\)/.*#\1#p')
      craftctl set version="$VERSION"
    prime:
      - usr/bin
      - usr/share/applications/org.duckstation.DuckStation.desktop
      - usr/share/icons/hicolor/512x512/apps/org.duckstation.DuckStation.png
      - usr/lib/libsoundtouch.so*
      - usr/lib/libcpuinfo.so*
      - usr/lib/libshaderc_shared.so*
      - usr/lib/libpng16.so*
      - usr/lib/libjpeg.so*
      - usr/lib/libSDL2-2.0.so*

  command-chain:
    after: [duckstation-fresh-app]
    plugin: dump
    source: ./command-chain/
    organize:
      unset-qt_qpa_platform: snap/command-chain/unset-qt_qpa_platform
